workflows:
  android-build:
    name: GATE ECE Master Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
      - name: Build Android App Bundle (AAB for Play Store)
        script: |
          flutter build appbundle --release --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - rrganesankamal10@gmail.com
        notify:
          success: true
          failure: true
